In [1]:
import numpy as np
import pandas as pd
from datetime import datetime

In [2]:
df_ufc_fighter_tott = pd.read_csv('ufc_fighters_statistics_2.csv')
fighter_summary = pd.read_csv('summary.csv')
df_ufc_event = pd.read_csv('ufc_event_details_processed.csv')
df_fight_results = pd.read_csv('ufc_fight_results_processed.csv')
df_fight_stats = pd.read_csv('ufc_fight_stats_processed.csv')

In [3]:
merged_df = pd.merge(df_ufc_fighter_tott, fighter_summary, left_on='name', right_on='Fighter', how='inner')

## Creating summary files of names & fighters' history

In [4]:
df_fight_results['BOUT'] = df_fight_results['BOUT'].str.lower().str.strip()
df_fight_results['BOUT'] = df_fight_results['BOUT'].str.replace("  vs.", " vs.", regex=False)
df_fight_stats['BOUT'] = df_fight_stats['BOUT'].str.lower().str.strip()
df_fight_results['EVENT'] = df_fight_results['EVENT'].str.lower().str.strip()
df_fight_stats['EVENT'] = df_fight_stats['EVENT'].str.lower().str.strip()

In [5]:
df_ufc_fighter_tott['name']= df_ufc_fighter_tott['name'].str.strip().str.lower()
fighter_summary['Fighter']= fighter_summary['Fighter'].str.strip().str.lower()

In [6]:
merged_df = pd.merge(df_ufc_fighter_tott, fighter_summary, left_on='name', right_on='Fighter', how='inner')

In [7]:
main_summary = merged_df.drop(columns=['Fighter', 'nickname'])

In [8]:
main_summary

,name,height_cm,weight_in_kg,reach_in_cm,stance,date_of_birth,wins,losses,draws,nc,total_matches
0,robert drysdale,190.50,92.99,NaN,Orthodox,1981-10-05,0,0,0,1,1
1,gerald strebendt,175.26,70.31,NaN,Orthodox,1979-03-01,0,1,0,0,1
2,neil grove,198.12,120.20,NaN,Orthodox,1971-01-18,0,1,0,0,1
3,bo nickal,185.42,83.91,193.04,Southpaw,1996-01-14,4,0,0,0,4
4,ian entwistle,165.10,61.23,NaN,Orthodox,1986-11-19,1,2,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...
2503,abner lloveras,180.34,70.31,NaN,NaN,NaN,0,1,0,0,1
2504,brian melancon,172.72,77.11,NaN,Orthodox,1982-05-28,1,1,0,0,2
2505,amaury bitetti,175.26,83.91,NaN,Orthodox,NaN,1,1,0,0,2
2506,john campetella,175.26,106.59,NaN,Orthodox,NaN,0,1,0,0,1
2507,andre pederneiras,172.72,70.31,NaN,Orthodox,1967-03-22,0,1,0,0,1

## Adding weightclass to the fight_stats for easier processing

In [12]:
fight_stats_with_weightclass = df_fight_stats.merge(

    df_fight_results[['EVENT', 'BOUT', 'weight_class','gender','is_title_bout']],

    on=['EVENT', 'BOUT'],

    how='left'
)

In [21]:
fight_stats_with_weightclass = fight_stats_with_weightclass.merge(

    df_ufc_event[['EVENT','DATE', 'LOCATION']],

    on=['EVENT'],

    how='left'
)

In [22]:
fight_stats_with_weightclass

,EVENT,BOUT,ROUND,FIGHTER,KD,SIG.STR. %,TD %,SUB.ATT,REV.,CTRL,...,total_clinch_land,total_ground_attempt,total_ground_land,total_head_attempt,total_head_land,weight_class,gender,is_title_bout,DATE,LOCATION
0,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,Round 1,colby covington,0.0,0.19,0.00,0.0,0.0,22.0,...,0.0,0.0,0.0,5.0,42.0,welterweight,0.0,0.0,12-14-24,"tampa, florida, usa"
1,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,Round 2,colby covington,0.0,0.38,0.33,0.0,0.0,88.0,...,0.0,2.0,2.0,13.0,43.0,welterweight,0.0,0.0,12-14-24,"tampa, florida, usa"
2,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,Round 3,colby covington,0.0,0.34,0.00,0.0,0.0,110.0,...,0.0,2.0,2.0,8.0,23.0,welterweight,0.0,0.0,12-14-24,"tampa, florida, usa"
3,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,Round 1,joaquin buckley,0.0,0.41,0.00,0.0,0.0,9.0,...,2.0,2.0,4.0,18.0,47.0,welterweight,0.0,0.0,12-14-24,"tampa, florida, usa"
4,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,Round 2,joaquin buckley,0.0,0.50,0.00,0.0,0.0,1.0,...,5.0,0.0,0.0,20.0,46.0,welterweight,0.0,0.0,12-14-24,"tampa, florida, usa"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37301,ufc 2: no way out,johnny rhodes vs. david levicki,Round 1,david levicki,0.0,0.80,0.00,0.0,0.0,0.0,...,2.0,1.0,1.0,4.0,5.0,open weight,0.0,0.0,03-11-94,"denver, colorado, usa"
37302,ufc 2: no way out,patrick smith vs. ray wizard,Round 1,patrick smith,0.0,1.00,0.00,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,open weight,0.0,0.0,03-11-94,"denver, colorado, usa"
37303,ufc 2: no way out,patrick smith vs. ray wizard,Round 1,ray wizard,0.0,1.00,0.00,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,open weight,0.0,0.0,03-11-94,"denver, colorado, usa"
37304,ufc 2: no way out,scott morris vs. sean daugherty,Round 1,scott morris,0.0,1.00,1.00,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,1.0,open weight,0.0,0.0,03-11-94,"denver, colorado, usa"
37305,ufc 2: no way out,scott morris vs. sean daugherty,Round 1,sean daugherty,0.0,0.00,0.00,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,2.0,open weight,0.0,0.0,03-11-94,"denver, colorado, usa"

In [17]:
fight_stats_with_weightclass['is_title_bout'].isnull()

0        False
1        False
2        False
3        False
4        False
         ...
37301    False
37302    False
37303    False
37304    False
37305    False
Name: is_title_bout, Length: 37306, dtype: bool

In [23]:
fight_stats_with_weightclass.to_csv('fight_stats_with_weghtclass_date_location.csv',index=False)